using Threads_OOP.Examples;

namespace Threads_OOP.Menu;

internal sealed record DemoItem(
    string Name,
    string MethodName,
    string SourceFile,
    string Description,
    Func<Task> Runner,
    bool Warning = false);

internal sealed record DemoCategory(string Name, string Icon, IReadOnlyList<DemoItem> Items);

internal static class DemoCatalog
{
    public static IReadOnlyList<DemoCategory> Categories { get; } = new List<DemoCategory>
    {
        new("Basic Threading", "🧵", new List<DemoItem>
        {
            new("Basic Thread with Join", nameof(ThreadingExamples.BasicThreadWithJoin),
                "ThreadingExamples.cs",
                "Creates a Thread, starts it, and waits for it to complete via Join().",
                () => Wrap(ThreadingExamples.BasicThreadWithJoin)),
            new("Basic Thread (no wait)", nameof(ThreadingExamples.BasicThreadNoWait),
                "ThreadingExamples.cs",
                "Starts a thread without waiting for it — shows fire-and-forget behavior.",
                () => Wrap(ThreadingExamples.BasicThreadNoWait)),
            new("Thread with Priority", nameof(ThreadingExamples.ThreadWithPriority),
                "ThreadingExamples.cs",
                "Demonstrates setting Thread.Priority to hint scheduling preference.",
                () => Wrap(ThreadingExamples.ThreadWithPriority)),
            new("ThreadPool QueueUserWorkItem", nameof(ThreadingExamples.ThreadPoolExample),
                "ThreadingExamples.cs",
                "Queues work onto the managed ThreadPool using QueueUserWorkItem.",
                () => Wrap(ThreadingExamples.ThreadPoolExample)),
            new("Background Thread", nameof(ThreadingExamples.BackgroundThreadExample),
                "ThreadingExamples.cs",
                "Shows IsBackground=true: process exits without waiting for the thread.",
                () => Wrap(ThreadingExamples.BackgroundThreadExample)),
        }),
        new("Tasks & async/await", "⚡", new List<DemoItem>
        {
            new("Basic Task", nameof(TaskExamples.BasicTaskExample), "TaskExamples.cs",
                "Launches a Task with Task.Run and awaits its completion.",
                TaskExamples.BasicTaskExample),
            new("Task with Return Value", nameof(TaskExamples.TaskWithReturnValue), "TaskExamples.cs",
                "Returns a value from a Task<T> and awaits the result.",
                TaskExamples.TaskWithReturnValue),
            new("Task Cancellation", nameof(TaskExamples.TaskCancellationExample), "TaskExamples.cs",
                "Uses CancellationTokenSource to cooperatively cancel a running Task.",
                TaskExamples.TaskCancellationExample),
            new("Task Continuation", nameof(TaskExamples.TaskContinuationExample), "TaskExamples.cs",
                "Chains work with ContinueWith after a Task finishes.",
                TaskExamples.TaskContinuationExample),
            new("Parallel Task Processing", nameof(TaskExamples.ParallelTaskProcessing), "TaskExamples.cs",
                "Runs multiple tasks concurrently and awaits them with Task.WhenAll.",
                TaskExamples.ParallelTaskProcessing),
            new("Fire and Forget", nameof(TaskExamples.FireAndForgetExample), "TaskExamples.cs",
                "Starts a Task without awaiting it — note exceptions can be lost.",
                TaskExamples.FireAndForgetExample),
            new("Task.WhenAny", nameof(TaskExamples.TaskWhenAnyExample), "TaskExamples.cs",
                "Waits for the first of several tasks to complete.",
                TaskExamples.TaskWhenAnyExample),
            new("AsyncLazy<T>", nameof(TaskExamples.AsyncLazyExample), "TaskExamples.cs",
                "Lazy async initialization pattern built on Lazy<Task<T>>.",
                TaskExamples.AsyncLazyExample),
            new("Stable Counter with Tasks", nameof(TaskExamples.TaskStableCounterExample), "TaskExamples.cs",
                "Increments a shared counter safely using Task and synchronization.",
                TaskExamples.TaskStableCounterExample),
        }),
        new("Synchronization", "🔒", new List<DemoItem>
        {
            new("Unstable (no sync)", nameof(SynchronizationExamples.UnstableExample),
                "SynchronizationExamples.cs",
                "Shows the race condition that occurs WITHOUT synchronization.",
                () => Wrap(SynchronizationExamples.UnstableExample)),
            new("Interlocked", nameof(SynchronizationExamples.InterlockedExample),
                "SynchronizationExamples.cs",
                "Fixes the race with Interlocked.Increment — atomic and fast.",
                () => Wrap(SynchronizationExamples.InterlockedExample)),
            new("lock statement", nameof(SynchronizationExamples.LockExample),
                "SynchronizationExamples.cs",
                "Uses C# lock to provide mutual exclusion on a shared section.",
                () => Wrap(SynchronizationExamples.LockExample)),
            new("SemaphoreSlim", nameof(SynchronizationExamples.SemaphoreExample),
                "SynchronizationExamples.cs",
                "Limits concurrency to N concurrent workers with SemaphoreSlim.",
                SynchronizationExamples.SemaphoreExample),
            new("ReaderWriterLockSlim", nameof(SynchronizationExamples.ReaderWriterLockExample),
                "SynchronizationExamples.cs",
                "Allows many readers OR one writer — great for read-heavy workloads.",
                () => Wrap(SynchronizationExamples.ReaderWriterLockExample)),
            new("Mutex", nameof(SynchronizationExamples.MutexExample),
                "SynchronizationExamples.cs",
                "OS-level mutual exclusion primitive (named, cross-process capable).",
                () => Wrap(SynchronizationExamples.MutexExample)),
            new("Monitor", nameof(SynchronizationExamples.MonitorExample),
                "SynchronizationExamples.cs",
                "Lower-level building block behind the lock keyword.",
                () => Wrap(SynchronizationExamples.MonitorExample)),
            new("volatile field", nameof(SynchronizationExamples.VolatileExample),
                "SynchronizationExamples.cs",
                "Shows volatile read/write semantics for a shared flag.",
                () => Wrap(SynchronizationExamples.VolatileExample)),
        }),
        new("Atomic Operations", "⚛", new List<DemoItem>
        {
            new("Interlocked.Increment / Decrement", nameof(AtomicExamples.InterlockedIncrementDecrement),
                "AtomicExamples.cs",
                "Atomic increment/decrement of a shared 32/64-bit integer.",
                () => Wrap(AtomicExamples.InterlockedIncrementDecrement)),
            new("Interlocked.Exchange", nameof(AtomicExamples.InterlockedExchange), "AtomicExamples.cs",
                "Atomically swaps a value and returns the original.",
                () => Wrap(AtomicExamples.InterlockedExchange)),
            new("Interlocked.CompareExchange", nameof(AtomicExamples.InterlockedCompareExchange),
                "AtomicExamples.cs",
                "CAS primitive — the foundation of most lock-free algorithms.",
                () => Wrap(AtomicExamples.InterlockedCompareExchange)),
            new("Interlocked.Add", nameof(AtomicExamples.InterlockedAdd), "AtomicExamples.cs",
                "Atomically adds a value to a shared integer.",
                () => Wrap(AtomicExamples.InterlockedAdd)),
            new("Interlocked.Read (64-bit)", nameof(AtomicExamples.InterlockedRead), "AtomicExamples.cs",
                "Atomic read of a 64-bit value on 32-bit architectures.",
                () => Wrap(AtomicExamples.InterlockedRead)),
            new("SpinLock", nameof(AtomicExamples.SpinLockExample), "AtomicExamples.cs",
                "Lightweight busy-wait lock for very short critical sections.",
                () => Wrap(AtomicExamples.SpinLockExample)),
            new("SpinWait", nameof(AtomicExamples.SpinWaitExample), "AtomicExamples.cs",
                "SpinWait helper for hybrid spin/yield waiting.",
                () => Wrap(AtomicExamples.SpinWaitExample)),
        }),
        new("Parallel Processing", "🧮", new List<DemoItem>
        {
            new("Parallel.For", nameof(ParallelExamples.ParallelForExample), "ParallelExamples.cs",
                "Parallelizes a for-loop across the ThreadPool.",
                () => Wrap(ParallelExamples.ParallelForExample)),
            new("Parallel.ForEach", nameof(ParallelExamples.ParallelForEachExample), "ParallelExamples.cs",
                "Parallelizes an IEnumerable<T> iteration.",
                () => Wrap(ParallelExamples.ParallelForEachExample)),
            new("Parallel.For with Options", nameof(ParallelExamples.ParallelForWithOptions),
                "ParallelExamples.cs",
                "Caps parallelism with ParallelOptions.MaxDegreeOfParallelism.",
                () => Wrap(ParallelExamples.ParallelForWithOptions)),
            new("Parallel.For with Cancellation", nameof(ParallelExamples.ParallelForWithCancellation),
                "ParallelExamples.cs",
                "Stops a parallel loop cooperatively via ParallelLoopState.Stop().",
                () => Wrap(ParallelExamples.ParallelForWithCancellation)),
            new("Parallel.Invoke", nameof(ParallelExamples.ParallelInvokeExample), "ParallelExamples.cs",
                "Runs several independent actions concurrently.",
                () => Wrap(ParallelExamples.ParallelInvokeExample)),
            new("PLINQ", nameof(ParallelExamples.PLINQExample), "ParallelExamples.cs",
                "Compares sequential LINQ vs .AsParallel().",
                () => Wrap(ParallelExamples.PLINQExample)),
            new("PLINQ AsOrdered", nameof(ParallelExamples.PLINQOrderedExample), "ParallelExamples.cs",
                "Preserves ordering in parallel queries using AsOrdered().",
                () => Wrap(ParallelExamples.PLINQOrderedExample)),
            new("PLINQ Aggregate", nameof(ParallelExamples.PLINQAggregateExample), "ParallelExamples.cs",
                "Parallel reduction using the four-argument Aggregate overload.",
                () => Wrap(ParallelExamples.PLINQAggregateExample)),
            new("TPL Dataflow", nameof(ParallelExamples.DataflowExample), "ParallelExamples.cs",
                "Builds a pipeline with TransformBlock and ActionBlock.",
                () => Wrap(ParallelExamples.DataflowExample)),
            new("Custom Partitioner", nameof(ParallelExamples.PartitionerExample), "ParallelExamples.cs",
                "Uses a load-balancing Partitioner for better work distribution.",
                () => Wrap(ParallelExamples.PartitionerExample)),
        }),
        new("Performance Comparisons", "📊", new List<DemoItem>
        {
            new("Sequential vs Parallel", nameof(PerformanceExamples.SequentialVsParallelComparison),
                "PerformanceExamples.cs",
                "Times the same workload run sequentially vs in parallel.",
                () => Wrap(PerformanceExamples.SequentialVsParallelComparison)),
            new("lock vs Interlocked", nameof(PerformanceExamples.LockVsInterlockedPerformance),
                "PerformanceExamples.cs",
                "Micro-benchmark: managed lock vs Interlocked.Increment.",
                () => Wrap(PerformanceExamples.LockVsInterlockedPerformance)),
            new("SpinLock vs lock", nameof(PerformanceExamples.SpinLockVsLockPerformance),
                "PerformanceExamples.cs",
                "Contention micro-benchmark: SpinLock vs the lock keyword.",
                () => Wrap(PerformanceExamples.SpinLockVsLockPerformance)),
            new("Task vs Thread", nameof(PerformanceExamples.TaskVsThreadPerformance),
                "PerformanceExamples.cs",
                "Creation/scheduling overhead of Task vs raw Thread.",
                PerformanceExamples.TaskVsThreadPerformance),
            new("Concurrent Collections", nameof(PerformanceExamples.ConcurrentCollectionsPerformance),
                "PerformanceExamples.cs",
                "Throughput of ConcurrentBag/Queue/Dictionary under contention.",
                () => Wrap(PerformanceExamples.ConcurrentCollectionsPerformance)),
            new("Context Switching Overhead", nameof(PerformanceExamples.ContextSwitchingOverhead),
                "PerformanceExamples.cs",
                "Demonstrates the cost of excessive thread context switching.",
                () => Wrap(PerformanceExamples.ContextSwitchingOverhead)),
        }),
        new("Advanced Patterns", "🧠", new List<DemoItem>
        {
            new("Producer / Consumer", nameof(AdvancedExamples.ProducerConsumerExample),
                "AdvancedExamples.cs",
                "BlockingCollection-based producer/consumer pipeline.",
                () => Wrap(AdvancedExamples.ProducerConsumerExample)),
            new("Deadlock Avoidance", nameof(AdvancedExamples.DeadlockAvoidanceExample),
                "AdvancedExamples.cs",
                "Orders lock acquisition to prevent a classic deadlock.",
                () => Wrap(AdvancedExamples.DeadlockAvoidanceExample)),
            new("Monitor.TryEnter", nameof(AdvancedExamples.MonitorTryEnterExample),
                "AdvancedExamples.cs",
                "Attempts to acquire a lock with a timeout using Monitor.TryEnter.",
                () => Wrap(AdvancedExamples.MonitorTryEnterExample)),
            new("Async Coordination", nameof(AdvancedExamples.AsyncCoordinationExample),
                "AdvancedExamples.cs",
                "Coordinates async work with TaskCompletionSource / SemaphoreSlim.",
                AdvancedExamples.AsyncCoordinationExample),
            new("Barrier", nameof(AdvancedExamples.BarrierExample), "AdvancedExamples.cs",
                "Uses Barrier to synchronize multiple threads at phase boundaries.",
                () => Wrap(AdvancedExamples.BarrierExample)),
            new("CountdownEvent", nameof(AdvancedExamples.CountdownEventExample),
                "AdvancedExamples.cs",
                "Signals completion when a counter reaches zero.",
                () => Wrap(AdvancedExamples.CountdownEventExample)),
            new("Channel<T>", nameof(AdvancedExamples.ChannelExample), "AdvancedExamples.cs",
                "Modern async producer/consumer with System.Threading.Channels.",
                AdvancedExamples.ChannelExample),
            new("Deadlock (⚠ hangs!)", nameof(AdvancedExamples.DeadlockExample),
                "AdvancedExamples.cs",
                "Intentionally deadlocks two threads to show the problem. " +
                "You will need to force close the app to exit this demo.",
                () => Wrap(AdvancedExamples.DeadlockExample),
                Warning: true),
        }),
    };

    private static Task Wrap(Action action)
    {
        action();
        return Task.CompletedTask;
    }
}
